[package]
name = 'dev'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'dev'

[dependencies]
extendr-api = '*'
reqwest = { version = "0.11.20", features = ["blocking"] }
