# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_dev_wrappers", use_symbols = TRUE, package_name = "dev")

#' @docType package
#' @usage NULL
#' @useDynLib dev, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

my_fun <- function() .Call(wrap__my_fun)


# nolint end
